import { AppShell } from '@mantine/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import SidePanel from '../components/SidePanel/SidePanel'
import ArmPanel from '../components/ArmPanel/ArmPanel'
import styles from '../styles/Home.module.css'
import { useRos } from '../utils/RosHooks'

const ROBOT_CAMERA_PORT = 8000

const Home: NextPage = () => {
  const ros = useRos()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        padding={"md"}
        aside={<SidePanel ros={ros} />}
        header={<h1 className={styles.title}>Welcome to ROS</h1>}
        navbar={<ArmPanel ros={ros} />}
      >
        <img className={styles.camera} src={`//${typeof window !== "undefined" ? window.location.hostname : "localhost"}:${ROBOT_CAMERA_PORT}/stream?topic=/head_camera/rgb/image_raw`} alt="Live Robot Camera" />  
      </AppShell>
    </div>
  )
}

export default Home