import { AppShell } from '@mantine/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import SetTorsoHeight from '../components/SetTorsoHeight/SetTorsoHeight'
import SidePanel from '../components/SidePanel/SidePanel'
import Status from '../components/Status/Status'
import styles from '../styles/Home.module.css'
import { useRos } from '../utils/RosHooks'

const ROBOT_CAMERA_PORT = 8000

const Home: NextPage = () => {
  const ros = useRos()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        padding={"md"}
        aside={<SidePanel ros={ros} />}
        header={<h1 className={styles.title}>Welcome to ROS</h1>}
      >
        <img className={styles.camera} src={`//${typeof window !== "undefined" ? window.location.hostname : "localhost"}:${ROBOT_CAMERA_PORT}/stream?topic=/head_camera/rgb/image_raw`} alt="Live Robot Camera" />  
      </AppShell>

      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home