import type { NextPage } from 'next'
import Head from 'next/head'
import Viewer from '../components/Viewer/Viewer'
import styles from '../styles/Home.module.css'
import { useRos } from '../utils/RosHooks'
const Home: NextPage = () => {

  const ros = useRos()
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Viewer ros={ros} />
      </main>
    </div>
  )
}

export default Home
